
server.port: 7003
server.error.include-message: always

logging:
  level:
    root: INFO
    io.github.chiol: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE




spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: docker

spring.datasource:
  url: jdbc:mysql://mysql/review-db

server:
  port: 8080